### ISSUE TITLE
ETSFormer: how to apply tau/delta?

### ISSUE THREAD

**Issue by inspirit** [thuml/Nonstationary_Transformers#10]
Hello,

Thanks a lot for a very interesting work, would you be so kind to provide some hints for how to apply learned tau/delta for ETSFormer architecture you mentioned in the paper?

**Comment by WenWeiTHU** [comment]
A very nice question!

Currently, we summarize the key point to re-incorporating non-stationary information as **approximating attention maps with raw inputs using current stationarized inputs and other statistics**. In Transformer, it works as a rescaling operation on the pre-softmax attention score. For Transformer variants, the implementations may differ on:

1. The operation: for normalization as stationarization, the rescaling operation is deduced
2. The granularity on attention: map-wise, row-wise, element-wise
3. The operand: where the de-stationary factors come/learn from

**Comment by WenWeiTHU** [comment]
For ETSformer, currently I have some some ideas like:
1. Frequency Attention: it seems also reasonable to rescale the attention on the frequency spectrum by the linear property of DFT
2. ES Attention: it can be a transformation more complex than rescaling since the stationarization here is differencing indeed. Also, the de-stationary factors are supposed to be learned from growth and seasonal component, rather than the raw series.
