### ISSUE TITLE
About decoder input

### ISSUE THREAD

**Issue by Yimjaehyun93** [thuml/Nonstationary_Transformers#28]
Hello
I have a question in the train part of exp/exp_main.py.
Is there a reason to fill the prediction part of the decoder's input with zeros instead of true values?
I know that in the general transformer learning process, true values are put in the decoder as well.
please answer about my question.
Thank you.

**Comment by WenWeiTHU** [comment]
The input of decoder is composed of two component: true values (past observerations as hints, length with label_len) and zero paddings (horizons to be predicted, length with pred_len). The decoder part is design to output the whole horizons to be predicted in one forwarding instead of the iterative way. (See Informer paper for the details). Therfore, the prediction part is all set as zeros padding.

**Comment by WenWeiTHU** [comment]
It is a horitorical analogy since the time series forecasting problem is firstly considered as the seq2seq problem like NLP. So that the enc-dec design is reservered in our implementation as a general framework for trm. In fact, several recent works have demostrated a simple MLP projector can function as well as the trm decoder part (PatchTST, TimesNet). In the enc-only structure, no extra imformations or past observerations as hints are no longer needed.

**Comment by Yimjaehyun93** [comment]
Thank you for your reply.

**Comment by WLW2980** [comment]
how to set label length?
