### ISSUE TITLE
Series Stationarization vs. Normalization

### ISSUE THREAD

**Issue by StatMixedML** [thuml/Nonstationary_Transformers#9]
Dear authors,

Thanks for making the code available of your interesting paper. 

When I was going through the paper, I found the usage of the term "Stationarization" a little confusing. In Section 3.1 you mention 

> To attenuate the non-stationarity of each input series, we conduct normalization on the temporal dimension (...)

Yet, I am not sure if normalization actually removes any of the non-stationarity. Let me illustrate this using the famous Air Passenger dataset, which is shown below.

![image](https://user-images.githubusercontent.com/41187941/201966068-43c433a4-0eb5-4963-a65c-b1d2a27ef539.png)

As a very sloppy definition "A time series is considered weakly stationary, if it has no trend or seasonality, constant variance over time, and a consistent auto-correlation over time". From the above plot, none of this is true for the data. This is confirmed by the Augmented-Dickey-Fuller (ADF) test

```python
Augmented Dickey-Fuller Test

data:  Monthly Airline Passenger Numbers
Dickey-Fuller = -1.5094, Lag order = 12, p-value = 0.7807
alternative hypothesis: stationary
```
as well as an Auto-ARIMA
```python
ARIMA(2,1,1)(0,1,0)[12]
```

If the series is normalized via `(y-mu)/sigma`, most of the factors that contribute to the non-stationarity are still present in the data, e.g., trend, seasonality, etc. as shown in the following plot.

![image](https://user-images.githubusercontent.com/41187941/201967506-2347b60b-b48f-46d6-aed0-e5603d46fb4c.png)

The fact that normalization does not remove or attenuate non-stationarity is also reflected by the ADF

```python
Augmented Dickey-Fuller Test

data:  Monthly Airline Passenger Numbers Normalized
Dickey-Fuller = -1.5094, Lag order = 12, p-value = 0.7807
alternative hypothesis: stationary
```
as well as an Auto-ARIMA
```python
ARIMA(2,1,1)(0,1,0)[12]
```

In fact, the ADF values are exactly the same as for the non-transformed data.

So instead of saying "Stationarization", one should rather use "Normalization". In fact, if the above series is supposed to be stationary, then one would need to use differencing + seasonal differencing as suggested by the Auto-ARIMA.

Have you tried to use (p,P) differencing for the evaluation of your models and compare the results to the proposed instance normalization? Also, using the residuals from a STL-decomposition might get you closer to a stationary series.

Looking very much forward to the discussion.

**Comment by WenWeiTHU** [comment]
Hello, thanks for your interest.

In fact,  **normalization on the whole series** has No effect on ADF and stationarity. However, the proposed instance normalization in our paper is conducted on every model’s input which is obtained by **shifting windows** on the whole time series, as shown in the following plot:

![image](https://user-images.githubusercontent.com/39073236/202078348-d61e1b8c-c8b3-4852-afa8-dcfff180af5a.png)

Since non-stationarity is characterized by continuous change of temperal statistics and distribution. The instance normaliztion makes time series in adjacent windows follow the same std and mean, which can highly attenuate the non-stationarity (decreased ADF) of the the whole series:

![image](https://user-images.githubusercontent.com/39073236/202078373-8184345c-44de-491f-9d6b-5105ae7c9e17.png)
(the **Stationaried** means processing by our proposed instance normalization)

**Comment by StatMixedML** [comment]
Thanks for the detalied clarification. I wasn't aware that you are using a sliding window normalization.
